version: '3.8'

services:

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=api_db
      - POSTGRES_USER=api_user
      - POSTGRES_PASSWORD=api_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    networks:
      - api-network

volumes:
  postgres_data:

networks:
  api-network:
    driver: bridge